name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release --verbose

    - name: Create tar.gz
      run: |
        mkdir -p artifacts
        cp target/release/rusty-player artifacts/
        tar -czvf artifacts/rusty-player.tar.gz -C artifacts rusty-player

    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rusty-player
        path: artifacts/rusty-player.tar.gz
