name: Linux RustyPlayer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Create artifact folder
      run: mkdir artifact

    - name: Copy config.json template to artifact folder
      run: cp config.json artifact/ 
    
    - name: Copy executable to artifact folder
      run: cp target/release/rusty-player artifact/ 

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: rusty-player-linux-x64
        path: artifact
