name: Linux RustyPlayer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release --verbose

    - name: Create tar.gz
      run: |
        mkdir -p artifacts
        cp target/release/rusty-player artifacts/
        tar -czvf artifacts/rusty-player.tar.gz -C artifacts rusty-player

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: rusty-player
        path: artifacts/rusty-player.tar.gz
