name: Windows RustyPlayer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable-x86_64-pc-windows-msvc

    - name: Build
      run: cargo build --release --verbose

    - name: Create tar.gz
      run: |
        mkdir artifacts
        copy target\release\rusty-player.exe artifacts\

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: rusty-player
        path: artifacts\rusty-player.tar.gz
